export default [
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ADALWARA KALAN (217951)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217951,
        location: 'ADALWARA KALAN',
        distance: 17,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ANCHER (217936)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217936,
        location: 'ANCHER',
        distance: 44,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BALRIYA (217943)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217943,
        location: 'BALRIYA',
        distance: 27,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHAGWATGARH (217948)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217948,
        location: 'BHAGWATGARH',
        distance: 26,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHEDOLA (217947)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217947,
        location: 'BHEDOLA',
        distance: 26,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BILOPA (217959)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217959,
        location: 'BILOPA',
        distance: 13,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BINJARI (217954)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217954,
        location: 'BINJARI',
        distance: 60,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHAUTH KA BARWARA (217944)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217944,
        location: 'CHAUTH KA BARWARA',
        distance: 23,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DEKWA (217958)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217958,
        location: 'DEKWA',
        distance: 15,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DIDAYACH (217938)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217938,
        location: 'DIDAYACH',
        distance: 38,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ISARDA (217931)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217931,
        location: 'ISARDA',
        distance: 51,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JHONPRA (217939)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217939,
        location: 'JHONPRA',
        distance: 34,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JONLA (217952)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217952,
        location: 'JONLA',
        distance: 16,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHIJURI (217887)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217887,
        location: 'KHIJURI',
        distance: 23,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KUSTALA (217922)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217922,
        location: 'KUSTALA',
        distance: 9,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MUI (217960)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217960,
        location: 'MUI',
        distance: 15,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PANCHOLAS (217883)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217883,
        location: 'PANCHOLAS',
        distance: 28,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PAODERA (217940)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217940,
        location: 'PAODERA',
        distance: 23,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RAJWANA (217941)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217941,
        location: 'RAJWANA',
        distance: 30,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RAWANJANA CHAUR (217888)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217888,
        location: 'RAWANJANA CHAUR',
        distance: 20,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RAWANJANA DUNGAR (217878)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217878,
        location: 'RAWANJANA DUNGAR',
        distance: 20,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SARSOP (217933)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217933,
        location: 'SARSOP',
        distance: 45,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHIWAR (217929)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217929,
        location: 'SHIWAR',
        distance: 50,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL TAPUR (217935)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217935,
        location: 'TAPUR',
        distance: 50,
    },
    {
        schoolName:
            'GOVT. SENIOR SECONDARY SCHOOL WARD NO. 1 VILLAGE AND POST\nMAHAPURA (217937)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217937,
        location: null,
        distance: 60,
    },
    {
        schoolName: 'MAHATMA GANDHI GOVT. SCHOOL CHAUTH KA BARWARA (217946)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217946,
        location: 'CHAUTH KA BARWARA',
        distance: 5,
    },
    {
        schoolName: 'MAHATMA GANDHI GOVT. SCHOOL SHIWAR (217930)',
        block: 'CHAUTH KA\nBARWARA',
        dist: 'S.MADHOPUR',
        nic: 217930,
        location: 'SHIWAR',
        distance: 50,
    },
]
