export default [
    {
        schoolName: 'GEETA DEVI AGRAWAL GGSSS ADARSH NAGAR A SAWAIMADHOPUR',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217970,
        location: null,
        distance: 0,
    },
    {
        schoolName: 'GOVT. GIRLS SENIOR SECONDARY SCHOOL MANTOWN (217962)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217962,
        location: 'MANTOWN',
        distance: 0,
    },
    {
        schoolName: 'GOVT. GIRLS SENIOR SECONDARY SCHOOL SOORWAL (217901)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217901,
        location: 'SOORWAL',
        distance: 11,
    },
    {
        schoolName:
            'GOVT. GIRLS SENIOR SECONDARY SCHOOL WARD CITY SAWAIMADHOPUR\n(217967)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217967,
        location: 'WARD CITY SAWAIMADHOPUR',
        distance: 0,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL AJNOTI (217896)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217896,
        location: 'AJNOTI',
        distance: 18,
    },
    {
        schoolName:
            'GOVT. SENIOR SECONDARY SCHOOL ALANPUR SAWAI MADHOPUR (217968)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217968,
        location: 'ALANPUR SAWAI MADHOPUR',
        distance: 0,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ATUN KALAN (217919)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217919,
        location: 'ATUN KALAN',
        distance: 7,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BADOLAS (217925)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217925,
        location: 'BADOLAS',
        distance: 27,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHADLAV (217912)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217912,
        location: 'BHADLAV',
        distance: 20,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHURIPAHARI (217851)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217851,
        location: 'BHURIPAHARI',
        distance: 35,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHAKERI (217907)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217907,
        location: 'CHAKERI',
        distance: 21,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHHARODA (217914)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217914,
        location: 'CHHARODA',
        distance: 15,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DHAMUN KALAN (217957)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217957,
        location: 'DHAMUN KALAN',
        distance: 8,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DUNGARI (217852)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217852,
        location: 'DUNGARI',
        distance: 40,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GAMBHIRA (217956)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217956,
        location: 'GAMBHIRA',
        distance: 30,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GOGOR (217904)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217904,
        location: 'GOGOR',
        distance: 18,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JARAWATA (217898)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217898,
        location: 'JARAWATA',
        distance: 20,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JATWARA KALAN (217895)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217895,
        location: 'JATWARA KALAN',
        distance: 19,
    },
    {
        schoolName:
            'GOVT. SENIOR SECONDARY SCHOOL JEENAPUR SAWAI MADOPUR RAJ.\n(217921)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217921,
        location: 'JEENAPUR SAWAI MADOPUR RAJ.',
        distance: 3,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KARMODA (217965)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217965,
        location: 'KARMODA',
        distance: 7,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHATUPURA (217927)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217927,
        location: 'KHATUPURA',
        distance: 4,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KUNDERA (217910)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217910,
        location: 'KUNDERA',
        distance: 17,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL LORWARA (217955)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217955,
        location: 'LORWARA',
        distance: 20,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAINPURA (217902)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217902,
        location: 'MAINPURA',
        distance: 15,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAKHOLI (217915)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217915,
        location: 'MAKHOLI',
        distance: 20,
    },
    {
        schoolName:
            'GOVT. SENIOR SECONDARY SCHOOL MANTOWN SAWAIMADHOPUR (217961)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217961,
        location: 'MANTOWN SAWAIMADHOPUR',
        distance: 0,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL NINDARDA (217928)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217928,
        location: 'NINDARDA',
        distance: 18,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL OLWADA (217964)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217964,
        location: 'OLWADA',
        distance: 27,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PACHIPLYA (217920)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217920,
        location: 'PACHIPLYA',
        distance: 5,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PADHANA (217905)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217905,
        location: 'PADHANA',
        distance: 5,
    },
    {
        schoolName:
            'GOVT. SENIOR SECONDARY SCHOOL RAMDI SAWAI MADHOPUR (217924)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217924,
        location: 'RAMDI SAWAI MADHOPUR',
        distance: 10,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RANWAL (217913)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217913,
        location: 'RANWAL',
        distance: 15,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SAWAI MADHOPUR (217966)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217966,
        location: 'SAWAI MADHOPUR',
        distance: 0,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SELU (217903)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217903,
        location: 'SELU',
        distance: 22,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHERPUR KHILCHIPUR (217917)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217917,
        location: 'SHERPUR KHILCHIPUR',
        distance: 7,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHYAMPURA (217909)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217909,
        location: 'SHYAMPURA',
        distance: 25,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SOORWAL (217900)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217900,
        location: 'SOORWAL',
        distance: 12,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SUNARI (217899)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217899,
        location: 'SUNARI',
        distance: 12,
    },
    {
        schoolName: 'MAHATMA GANDHI GOVT. SCHOOL KHILCHIPUR (217916)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217916,
        location: 'KHILCHIPUR',
        distance: 9,
    },
    {
        schoolName:
            'MAHATMA GANDHI GOVT. SCHOOL, SAHUNAGAR, SAWAI MADHOPUR (217971)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217971,
        location: 'SAHUNAGAR, SAWAI MADHOPUR',
        distance: 0,
    },
    {
        schoolName:
            'SHAHEED BABU LAL MEENA GSSS ENDWA WARD NO. 3 NASIR BABA KE\nMANDIR KE PASS',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217963,
        location: null,
        distance: 0,
    },
    {
        schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHERPUR (217918)',
        block: 'SAWAI\nMADHOPUR',
        dist: 'S.MADHOPUR',
        nic: 217918,
        location: 'SHERPUR',
        distance: 9,
    },
]
