export default {
    distanceData: [
        {
            schoolName: 'GEETA DEVI AGRAWAL GGSSS ADARSH NAGAR A SAWAIMADHOPUR',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217970,
            location: null,
            distance: 0,
            id: 39,
        },
        {
            schoolName: 'GOVT. GIRLS SENIOR SECONDARY SCHOOL MANTOWN (217962)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217962,
            location: 'MANTOWN',
            distance: 0,
            id: 40,
        },
        {
            schoolName:
                'GOVT. GIRLS SENIOR SECONDARY SCHOOL WARD CITY SAWAIMADHOPUR\n(217967)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217967,
            location: 'WARD CITY SAWAIMADHOPUR',
            distance: 0,
            id: 42,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL ALANPUR SAWAI MADHOPUR (217968)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217968,
            location: 'ALANPUR SAWAI MADHOPUR',
            distance: 0,
            id: 44,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL MANTOWN SAWAIMADHOPUR (217961)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217961,
            location: 'MANTOWN SAWAIMADHOPUR',
            distance: 0,
            id: 64,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SAWAI MADHOPUR (217966)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217966,
            location: 'SAWAI MADHOPUR',
            distance: 0,
            id: 71,
        },
        {
            schoolName:
                'MAHATMA GANDHI GOVT. SCHOOL, SAHUNAGAR, SAWAI MADHOPUR (217971)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217971,
            location: 'SAHUNAGAR, SAWAI MADHOPUR',
            distance: 0,
            id: 78,
        },
        {
            schoolName:
                'SHAHEED BABU LAL MEENA GSSS ENDWA WARD NO. 3 NASIR BABA KE\nMANDIR KE PASS',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217963,
            location: null,
            distance: 0,
            id: 79,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL JEENAPUR SAWAI MADOPUR RAJ.\n(217921)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217921,
            location: 'JEENAPUR SAWAI MADOPUR RAJ.',
            distance: 3,
            id: 57,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHATUPURA (217927)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217927,
            location: 'KHATUPURA',
            distance: 4,
            id: 59,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL KHIDARPUR JADON (217853)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217853,
            location: 'KHIDARPUR JADON',
            distance: 5,
            id: 23,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PACHIPLYA (217920)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217920,
            location: 'PACHIPLYA',
            distance: 5,
            id: 67,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PADHANA (217905)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217905,
            location: 'PADHANA',
            distance: 5,
            id: 68,
        },
        {
            schoolName:
                'MAHATMA GANDHI GOVT. SCHOOL CHAUTH KA BARWARA (217946)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217946,
            location: 'CHAUTH KA BARWARA',
            distance: 5,
            id: 106,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ATUN KALAN (217919)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217919,
            location: 'ATUN KALAN',
            distance: 7,
            id: 45,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KARMODA (217965)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217965,
            location: 'KARMODA',
            distance: 7,
            id: 58,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL SHERPUR KHILCHIPUR (217917)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217917,
            location: 'SHERPUR KHILCHIPUR',
            distance: 7,
            id: 73,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DHAMUN KALAN (217957)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217957,
            location: 'DHAMUN KALAN',
            distance: 8,
            id: 51,
        },
        {
            schoolName: 'MAHATMA GANDHI GOVT. SCHOOL KHILCHIPUR (217916)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217916,
            location: 'KHILCHIPUR',
            distance: 9,
            id: 77,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHERPUR (217918)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217918,
            location: 'SHERPUR',
            distance: 9,
            id: 80,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KUSTALA (217922)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217922,
            location: 'KUSTALA',
            distance: 9,
            id: 95,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GOTHRA (217871)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217871,
            location: 'GOTHRA',
            distance: 10,
            id: 18,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHANDEWALA (217891)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217891,
            location: 'KHANDEWALA',
            distance: 10,
            id: 21,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL RAMDI SAWAI MADHOPUR (217924)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217924,
            location: 'RAMDI SAWAI MADHOPUR',
            distance: 10,
            id: 69,
        },
        {
            schoolName: 'GOVT. GIRLS SENIOR SECONDARY SCHOOL SOORWAL (217901)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217901,
            location: 'SOORWAL',
            distance: 11,
            id: 41,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SOORWAL (217900)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217900,
            location: 'SOORWAL',
            distance: 12,
            id: 75,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SUNARI (217899)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217899,
            location: 'SUNARI',
            distance: 12,
            id: 76,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BILOPA (217959)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217959,
            location: 'BILOPA',
            distance: 13,
            id: 86,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL HALONDA (226740)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 226740,
            location: 'HALONDA',
            distance: 14,
            id: 19,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHHARODA (217914)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217914,
            location: 'CHHARODA',
            distance: 15,
            id: 50,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAINPURA (217902)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217902,
            location: 'MAINPURA',
            distance: 15,
            id: 62,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RANWAL (217913)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217913,
            location: 'RANWAL',
            distance: 15,
            id: 70,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DEKWA (217958)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217958,
            location: 'DEKWA',
            distance: 15,
            id: 89,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MUI (217960)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217960,
            location: 'MUI',
            distance: 15,
            id: 96,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JONLA (217952)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217952,
            location: 'JONLA',
            distance: 16,
            id: 93,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KUNDERA (217910)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217910,
            location: 'KUNDERA',
            distance: 17,
            id: 60,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ADALWARA KALAN (217951)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217951,
            location: 'ADALWARA KALAN',
            distance: 17,
            id: 81,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL AJNOTI (217896)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217896,
            location: 'AJNOTI',
            distance: 18,
            id: 43,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GOGOR (217904)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217904,
            location: 'GOGOR',
            distance: 18,
            id: 54,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL NINDARDA (217928)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217928,
            location: 'NINDARDA',
            distance: 18,
            id: 65,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JATWARA KALAN (217895)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217895,
            location: 'JATWARA KALAN',
            distance: 19,
            id: 56,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHADLAV (217912)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217912,
            location: 'BHADLAV',
            distance: 20,
            id: 47,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JARAWATA (217898)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217898,
            location: 'JARAWATA',
            distance: 20,
            id: 55,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL LORWARA (217955)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217955,
            location: 'LORWARA',
            distance: 20,
            id: 61,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAKHOLI (217915)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217915,
            location: 'MAKHOLI',
            distance: 20,
            id: 63,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL RAWANJANA CHAUR (217888)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217888,
            location: 'RAWANJANA CHAUR',
            distance: 20,
            id: 100,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL RAWANJANA DUNGAR (217878)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217878,
            location: 'RAWANJANA DUNGAR',
            distance: 20,
            id: 101,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHAKERI (217907)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217907,
            location: 'CHAKERI',
            distance: 21,
            id: 49,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DUMODA (217879)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217879,
            location: 'DUMODA',
            distance: 22,
            id: 15,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SELU (217903)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217903,
            location: 'SELU',
            distance: 22,
            id: 72,
        },
        {
            schoolName:
                'ASHOK GOVT. SENIOR SECONDARY SCHOOL PHALODI QUARRY TODRA\n(217886)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217886,
            location: 'PHALODI QUARRY TODRA',
            distance: 23,
            id: 1,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PHALODI (217880)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217880,
            location: 'PHALODI',
            distance: 23,
            id: 31,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL CHAUTH KA BARWARA (217944)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217944,
            location: 'CHAUTH KA BARWARA',
            distance: 23,
            id: 88,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHIJURI (217887)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217887,
            location: 'KHIJURI',
            distance: 23,
            id: 94,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PAODERA (217940)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217940,
            location: 'PAODERA',
            distance: 23,
            id: 98,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ALLAPUR (217875)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217875,
            location: 'ALLAPUR',
            distance: 24,
            id: 4,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHHAN (217876)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217876,
            location: 'CHHAN',
            distance: 25,
            id: 11,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHYAMPURA (217909)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217909,
            location: 'SHYAMPURA',
            distance: 25,
            id: 74,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHAGWATGARH (217948)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217948,
            location: 'BHAGWATGARH',
            distance: 26,
            id: 84,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHEDOLA (217947)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217947,
            location: 'BHEDOLA',
            distance: 26,
            id: 85,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BADOLAS (217925)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217925,
            location: 'BADOLAS',
            distance: 27,
            id: 46,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL OLWADA (217964)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217964,
            location: 'OLWADA',
            distance: 27,
            id: 66,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BALRIYA (217943)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217943,
            location: 'BALRIYA',
            distance: 27,
            id: 83,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SAWAIGANJ (464336)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 464336,
            location: 'SAWAIGANJ',
            distance: 28,
            id: 34,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL PANCHOLAS (217883)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217883,
            location: 'PANCHOLAS',
            distance: 28,
            id: 97,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DAULATPURA (217873)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217873,
            location: 'DAULATPURA',
            distance: 30,
            id: 14,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL LAHSODA (217885)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217885,
            location: 'LAHSODA',
            distance: 30,
            id: 26,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GAMBHIRA (217956)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217956,
            location: 'GAMBHIRA',
            distance: 30,
            id: 53,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RAJWANA (217941)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217941,
            location: 'RAJWANA',
            distance: 30,
            id: 99,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RAMPURA (217884)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217884,
            location: 'RAMPURA',
            distance: 33,
            id: 32,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHANPUR (217882)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217882,
            location: 'KHANPUR',
            distance: 34,
            id: 22,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAI KALAN (217893)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217893,
            location: 'MAI KALAN',
            distance: 34,
            id: 27,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL JHONPRA (217939)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217939,
            location: 'JHONPRA',
            distance: 34,
            id: 92,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHITARA (217881)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217881,
            location: 'CHITARA',
            distance: 35,
            id: 12,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL PALI  KHANDAR  SAWAI MADHOPUR\n(217892)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217892,
            location: 'PALI  KHANDAR  SAWAI MADHOPUR',
            distance: 35,
            id: 30,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BHURIPAHARI (217851)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217851,
            location: 'BHURIPAHARI',
            distance: 35,
            id: 48,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DIDAYACH (217938)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217938,
            location: 'DIDAYACH',
            distance: 38,
            id: 90,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL MAY KHURD (495305)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 495305,
            location: 'MAY KHURD',
            distance: 40,
            id: 28,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL DUNGARI (217852)',
            block: 'SAWAI\nMADHOPUR',
            dist: 'S.MADHOPUR',
            nic: 217852,
            location: 'DUNGARI',
            distance: 40,
            id: 52,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GANDAWAR (217894)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217894,
            location: 'GANDAWAR',
            distance: 41,
            id: 16,
        },
        {
            schoolName: 'GOVT. GIRLS SENIOR SECONDARY SCHOOL KHANDAR (217869)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217869,
            location: 'KHANDAR',
            distance: 42,
            id: 2,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL AKASHAYGARH (217861)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217861,
            location: 'AKASHAYGARH',
            distance: 42,
            id: 3,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL BAHRAWANDA KHURD TEHSIL KHANDAR\nSAWAI MADHOPUR (217863)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217863,
            location: null,
            distance: 42,
            id: 6,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KHANDAR (217868)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217868,
            location: 'KHANDAR',
            distance: 42,
            id: 20,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ANCHER (217936)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217936,
            location: 'ANCHER',
            distance: 44,
            id: 82,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SARSOP (217933)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217933,
            location: 'SARSOP',
            distance: 45,
            id: 102,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL GOTH BIHARI (217877)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217877,
            location: 'GOTH BIHARI',
            distance: 47,
            id: 17,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BARNAWADA (217867)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217867,
            location: 'BARNAWADA',
            distance: 48,
            id: 9,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL VAHARWANDA KALN (217874)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217874,
            location: 'VAHARWANDA KALN',
            distance: 50,
            id: 38,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SHIWAR (217929)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217929,
            location: 'SHIWAR',
            distance: 50,
            id: 103,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL TAPUR (217935)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217935,
            location: 'TAPUR',
            distance: 50,
            id: 104,
        },
        {
            schoolName: 'MAHATMA GANDHI GOVT. SCHOOL SHIWAR (217930)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217930,
            location: 'SHIWAR',
            distance: 50,
            id: 107,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ISARDA (217931)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217931,
            location: 'ISARDA',
            distance: 51,
            id: 91,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL ANIYALA (217870)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217870,
            location: 'ANIYALA',
            distance: 54,
            id: 5,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL NAYPUR (217866)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217866,
            location: 'NAYPUR',
            distance: 54,
            id: 29,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SAWATA (217890)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217890,
            location: 'SAWATA',
            distance: 57,
            id: 35,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL SINGOR KALAN (217889)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217889,
            location: 'SINGOR KALAN',
            distance: 59,
            id: 36,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL CHITOLA (217864)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217864,
            location: 'CHITOLA',
            distance: 60,
            id: 13,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BINJARI (217954)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217954,
            location: 'BINJARI',
            distance: 60,
            id: 87,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL WARD NO. 1 VILLAGE AND POST\nMAHAPURA (217937)',
            block: 'CHAUTH KA\nBARWARA',
            dist: 'S.MADHOPUR',
            nic: 217937,
            location: null,
            distance: 60,
            id: 105,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BALER (217856)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217856,
            location: 'BALER',
            distance: 62,
            id: 8,
        },
        {
            schoolName:
                'GOVT. SENIOR SECONDARY SCHOOL BICHPURI GUJRAN (217860)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217860,
            location: 'BICHPURI GUJRAN',
            distance: 64,
            id: 10,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL TALAWARA (217865)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217865,
            location: 'TALAWARA',
            distance: 64,
            id: 37,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL BAJOLI (217854)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217854,
            location: 'BAJOLI',
            distance: 65,
            id: 7,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KUREDI (217857)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217857,
            location: 'KUREDI',
            distance: 70,
            id: 25,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL RODAWAD (217858)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217858,
            location: 'RODAWAD',
            distance: 70,
            id: 33,
        },
        {
            schoolName: 'GOVT. SENIOR SECONDARY SCHOOL KOSARA CHARETA (217859)',
            block: 'KHANDAR',
            dist: 'S.MADHOPUR',
            nic: 217859,
            location: 'KOSARA CHARETA',
            distance: 100,
            id: 24,
        },
    ],
    selectedData: [],
}
